name: Build and Push Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Docker build
        run: |
          IMAGE_TAG=latest
          docker build -t 592524167743.dkr.ecr.us-east-2.amazonaws.com/ecr-repo:$IMAGE_TAG .

      - name: Docker push
        run: |
          IMAGE_TAG=latest
          docker push 592524167743.dkr.ecr.us-east-2.amazonaws.com/ecr-repo:$IMAGE_TAG
